### ISSUE TITLE
This plugin is incompatible with waterfox error

### ISSUE THREAD

**Issue by olivertzeng** [KatsuteDev/GitHub-Red-Issues#140]
### Operating System

Arch Linux

### Browser

WaterfoxLimited Waterfox G6.0.9

### Extension Version

8.0.0

### Theme

Light

### Components

- [ ] Pinned issues
- [ ] Issues
- [ ] Issue timeline
- [ ] Issues tab
- [ ] Issue hovercard
- [ ] Pulls
- [ ] Pull timeline
- [ ] Pull hovercard
- [ ] Tasklist
- [ ] Discussions
- [ ] Subscriptions
- [ ] Search
- [ ] Print
- [ ] Project Boards
- [ ] Project Tables
- [ ] Insights
- [X] Other (please specify)

### Issue

![圖片](https://github.com/KatsuteDev/GitHub-Red-Issues/assets/86348833/527e5f46-9114-4584-8d55-4991da7216ea)

### How to replicate

install the latest waterfox
install this
profit(?)

**Comment by Katsute** [comment]
![image](https://github.com/KatsuteDev/GitHub-Red-Issues/assets/58778985/9faab2c3-b681-4761-8dc3-140934dd37ca)

This addon requires Firefox > 121.0, Waterfox is using 115.0
