### ISSUE TITLE
Print label on closed issue have diffrent color

### ISSUE THREAD

**Issue by krystian3w** [KatsuteDev/GitHub-Red-Issues#59]
### Operating System

Windows 7

### Browser

Firefox / Edge

### Extension Version

3.3

### Components

- [ ] Pinned issues
- [X] Closed issues
- [ ] Issue timeline
- [ ] Issues tab
- [ ] Issue hovercard
- [ ] Closed pulls
- [ ] Pull timeline
- [ ] Pull hovercard
- [ ] Subscriptions
- [ ] Search
- [ ] Projects
- [ ] Projects (beta)
- [ ] Insights
- [ ] Other (please specify)

### Issue

Printed issues have purple label under header

![](https://user-images.githubusercontent.com/35370833/185250531-9d7737ce-0bf1-4ef5-803d-7ccde5e05070.png)

### How to replicate

Ctrl + P with enabled fancy print preview

**Comment by Katsute** [comment]
Seems to been an issue with the `@media print` selector overriding this extension's css, will investigate.

https://stackoverflow.com/a/29962072

**Comment by Katsute** [comment]
@mashiro-san create a branch fix print
